# Generated by Django 5.2.8 on 2025-12-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название направления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='history/', verbose_name='Изображение')),
                ('years', models.CharField(max_length=100, verbose_name='Годы реализации')),
                ('location', models.CharField(max_length=200, verbose_name='География')),
            ],
            options={
                'verbose_name': 'Историческая линия',
                'verbose_name_plural': 'Исторические линии',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('role', models.CharField(max_length=200, verbose_name='Роль в проекте')),
                ('position', models.CharField(max_length=200, verbose_name='Должность/Место учебы')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на ВК')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
