# Generated by Django 5.2.8 on 2025-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_news_image_newsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={'ordering': ['order'], 'verbose_name': 'Фото новости', 'verbose_name_plural': 'Фотографии новостей'},
        ),
        migrations.AddField(
            model_name='news',
            name='display_style',
            field=models.CharField(choices=[('grid', 'Сетка'), ('slider', 'Слайдер')], default='grid', max_length=10, verbose_name='Стиль отображения галереи'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
