# Generated by Django 5.2.8 on 2025-12-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_newsimage_options_news_display_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.AddField(
            model_name='news',
            name='main_content',
            field=models.TextField(default='', verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
    ]
